### ISSUE TITLE
Update to use v0.1.89

### ISSUE THREAD

**Issue by dBitech** [mapcomponents/template#1]
The template should be kept up-to-date to reflect the newest/latest supported versions of react & mapcomponets. 

Currently when trying to update to v0.1.89 the following error is returned:
```
> vite --host

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.0.11  ready in 217 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.1.84:5173/
  ➜  Network: http://172.27.0.1:5173/
  ➜  Network: http://172.20.20.1:5173/
  ➜  press h + enter to show help
✘ [ERROR] Could not resolve "sql.js"

    node_modules/@mapcomponents/react-maplibre/dist/index.esm.js:71:24:
      71 │ var initSqlJs = require('sql.js');
         ╵                         ~~~~~~~~

  You can mark the path "sql.js" as external to exclude it from the bundle, which will remove this
  error and leave the unresolved path in the bundle. You can also surround this "require" call with
  a try/catch block to handle this failure at run-time instead of bundle-time.
```
Further investigation shows that this was introduced in [v0.1.81](https://github.com/mapcomponents/react-map-components-maplibre/compare/v0.1.80...v0.1.81)

**Comment by cioddi** [comment]
I encountered that error two days ago. It was a dependency of the mbtiles protocol handler, which was removed temporarily until a better solution is found that does not force you to use SQL.js.
The latest version 0.1.94 fixes this

**Comment by cioddi** [comment]
fixed by https://github.com/mapcomponents/template/commit/e538c468375555dc651831269403333e03804350
